/** Inkfish sync core — pure TS shared by the Mac app and the Android app. See docs/sync.md. */
export { sha256 } from './hash'
export { utf8Encode, utf8Decode, toBase64, fromBase64, toHex } from './bytes'
export { merge3, mergeText, lcsPairs } from './diff3'
export { mergeNote, mergeDaily, conflictPath, splitFrontmatter } from './note'
export { plan, mergeKind, ignored, neededFromRemote, resolveMerge } from './plan'
export type { Entry, Manifest, Base, Op, MergeKind, Write } from './plan'
export * from './protocol'
export { runSync, encodeFiles, decodeFiles, bigDeletion, SyncHeld, GUARD_MIN, GUARD_SHARE } from './engine'
export type { BigDelete, GuardChoice } from './engine'
export type { SyncFs, Remote, SyncState, SyncReport } from './engine'
export { createHandler, parseHello } from './server'
export type { ServerHost, PeerRecord, PendingPair, HttpResult } from './server'
export { findMac, hello, pairWithMac, httpRemote, markDone } from './client'
export type { Fetch, MacPeer } from './client'
export { appendCapped, summarize, shortError, SYNC_LOG_CAP } from './log'
export type { SyncLogEntry, SyncLogKind } from './log'
